# Generated by Django 2.2.10 on 2020-03-24 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_name',
            field=models.CharField(max_length=1000, verbose_name='название ответа'),
        ),
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='testing.StudTest', verbose_name='название теста'),
        ),
        migrations.CreateModel(
            name='GroupTest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='login.Group')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='testing.StudTest')),
            ],
        ),
    ]
