# Generated by Django 2.2.10 on 2020-03-25 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_auto_20200325_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionresults',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='questions',
        ),
        migrations.AddField(
            model_name='answerresults',
            name='question_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testing.QuestionResults'),
        ),
        migrations.AddField(
            model_name='questionresults',
            name='test_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testing.TestResult'),
        ),
        migrations.AlterField(
            model_name='answerresults',
            name='answer_result',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='testing.Answer'),
        ),
        migrations.AlterField(
            model_name='questionresults',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='testing.Question'),
        ),
    ]
