# Generated by Django 2.2.10 on 2020-03-23 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.TextField(verbose_name='название группы')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=200, verbose_name='логин/фамилия студента')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='login.Group', verbose_name='группа')),
            ],
        ),
    ]
